Correct behaviors but not labelled.

diff --git a/Tools/Makefile b/Tools/Makefile
--- a/Tools/Makefile
+++ b/Tools/Makefile
@@ -3,23 +3,28 @@ my_cidr_check = \
   test "$(1)" != "1" || (echo $(2) | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$$' || \
   (echo "Value '$(2)' must be in valid CIDR notation" && exit 1))
 
-BAD_CIDR = 192.168.1.23/
 
 
-basic_negative_check:
-	echo I want this to succeed..
-	! false
-	echo And I want this to fail
-	! true
+
+GOOD_CIDR = 192.168.1.23/23
+
+BAD_CIDR = xyvvv
+
+
+basic_negative_cidr:
+	echo "First test..."
+	$(call my_cidr_check,1,$(GOOD_CIDR))
+	echo "Second test..."
+	! $(call my_cidr_check,1,$(BAD_CIDR))
 	echo "test passed"
 
 
+basic_negative_check:
+	echo "First test..."
+	! false || { echo "ERROR: Command failed as expected - continuing"; false; }
+	echo "Second test..."
+	! true || { echo "ERROR: Command passed when it should fail!"; exit 1; }
+	echo "test passed"
 
-test-invalid-prefix:
-	echo "Testing CIDR with invalid prefix $(BAD_CIDR)"
-	$(call my_cidr_check,1,$(BAD_CIDR)); echo retcode be $$?
-	echo next
-	@($(call my_cidr_check,1,$(BAD_CIDR)) && exit 13) || true
-	echo "Class C CIDR format test passed"
 
 
